CDC2017 <- read_excel("G:/R_CDC/result/A0/CDC2017.xlsx", 
											col_types = c("text", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "text", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "text", "numeric", "numeric", 
																		"numeric", "text", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"text", "numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "text", "text", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "text", "numeric", "text", 
																		"numeric", "text", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric", "numeric", "numeric", 
																		"numeric"))
View(CDC2017)